on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run WDIO tests
    steps:
    - name: Start Selenoid Server
      uses: Xotabu4/selenoid-github-action@v1
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm ci  
    - name: Start Tests
      run: npm test
    - name: Create Report
      run: npm run report
    - uses: actions/upload-artifact@v1
      with:
        name: allure-report
        path: ./allure-report