on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run WDIO tests
    steps:
    - uses: actions/checkout@v1
    - run: npm ci  
    - name: Start Selenoid Server
      uses: Xotabu4/selenoid-github-action@v1
    - name: npm test
      run: npm test