on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run WDIO tests
    steps:
    - name: start selenoid
      uses: Xotabu4/selenoid-github-action@v1
    - name: npm test
      run: npm test